accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from . forms import UserLoginForm

app_name = 'users'

urlpatterns = [
path('register/', views.account_register, name='register'),
path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                form_class=UserLoginForm), name='login'),

path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

ciods/urls.py
from django.urls import path
from . import views

app_name = 'ciods'

urlpatterns = [
path('',views.ciods, name = 'ciods'),
path('pulblication/',views.pulblication, name = 'pulblication'),

]

virhost_lncr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ciods.urls')),
    path('contact/',include('contact.urls')),
    path('accounts/', include('accounts.urls', namespace='users')),
    path('drug_resistant/', include('drug_resistant.urls', namespace='drug_resistant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                         PermissionsMixin)
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, username, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username,
                          **other_fields)
        user.set_password(password)
        user.save()
        return user


class UserBase(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=150)
    first_name = models.CharField(max_length=150, blank=True)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, null = True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = "Accounts"
        verbose_name_plural = "Accounts"

    def __str__(self):
        return self.username

# class UserDetails(models.Model):
#     user = models.ForeignKey(UserBase, on_delete=models.CASCADE)
#     country = CountryField()
#     phone_number = models.CharField(max_length=15, blank=True)
#     postcode = models.CharField(max_length=12, blank=True)
#     address_line_1 = models.CharField(max_length=150, blank=True)
#     address_line_2 = models.CharField(max_length=150, blank=True)
#     town_city = models.CharField(max_length=150, blank=True)
#     # User Status
#     is_active = models.BooleanField(default=True)
#     updated = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from .models import UserBase
from django.contrib.auth.forms import AuthenticationForm

class RegistrationForm(forms.ModelForm):

    username = forms.CharField(
        label='Full Name', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={
        'required': 'Sorry, you will need an email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = UserBase
        fields = ('username', 'email',)

    def clean_username(self):
        username = self.cleaned_data['username']
        return username

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserBase.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another Email, that is already taken')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'login-pwd',
        }
    ))

accounts/views.py
from django.shortcuts import render
from . forms import RegistrationForm
from django.shortcuts import redirect, render


def account_register(request):
    # if request.user.is_authenticated:
    #     return redirect('/')

    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.save()
            return redirect('users:login')

    else:
        registerForm = RegistrationForm()

    return render(request, 'accounts/register.html', {'form': registerForm})

templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown link
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      {% block content %}


      {% endblock %}
    
</body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}

<style>
    .container-fluid {
        max-width: 100%;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6  mx-auto">
                            <form class="account-form p-4 rounded" action="{% url 'users:login' %}" method="post">

                                {% csrf_token %}
                                <h3 class="mb-4">Sign In</h3>

                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Username or Password not correct!
                                </div>
                                {% endif %}

                                <label class="form-label">{{ form.username.label}}</label>
                                {{ form.username}}

                                <label class="form-label">{{ form.password.label}}</label>
                                {{ form.password}}
                                <div class="d-grid gap-2">
                                    <input type="hidden" name="next" value="{{ next }}">
                                    <button class="btn btn-primary py-2 mb-4 mt-5 fw-bold" type="submit" value="Log-in">Sign in
                                    </button>
                                </div>
                                <p class="text-center pb-3">
                                    <a href="{% url "users:register" %}">Create an account</a>
                                </p>
                            </form>
                            <p class="small text-center pt-4">
                                {% comment %} <a href="{% url "password_reset" %}">Forgotten Password?</a> {% endcomment %}
                            </p>
                            <p class="small text-center">
                                {% comment %} <a href="{% url "users:register" %}">Help Center?</a> {% endcomment %}
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/accounts/register.html
{% extends 'proteome/base.html' %}

{% block content %}


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7  mx-auto">
                             <form class="account-form p-4 rounded col-lg-10 mx-auto" action="." method="post">
                                {% csrf_token %}
                                <h3 class="mb-2 font-weight-bold">Create an account</h3>
                                <p class="mb-4">It's free and only takes a minute.</p>

                                {% if form.errors %}
                                <p>Please correct the following errors:</p>
                                {% for field in form %}
                                {% if field.errors %}
                                <div class="alert alert-primary" role="alert">
                                {{ field.label }}: {{ field.errors|striptags }}
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}

                                <label>{{ form.username.label }}<span class="text-muted small">
                                        (Required)</span></label>
                                {{ form.username }}
                                <label>{{ form.email.label}}<span class="text-muted small">
                                        (Required)</span></label>
                                {{ form.email }}
                                <label>{{ form.password.label}}<span class="text-muted mb-4">
                                        </span></label>
                                <small class="form-text text-muted mb-4 small">
                                    At least 8 characters and 1 digit
                                </small>
                                {{ form.password }}
                                <label>{{ form.password2.label}}<span class="text-muted small">
                                        (Required)</span></label>
                                {{ form.password2 }}
                                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw500 w-100" type="submit">Register</button>
                                <p class="text-center">
                                    <a href="{% url 'users:login' %}">Already have an account?</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>




{% endblock content %}