ciods/urls.py
from django.urls import path
from . import views

app_name = 'ciods'

urlpatterns = [
path('',views.ciods, name = 'ciods'),
path('pulblication/',views.pulblication, name = 'pulblication'),

]

drug_resistant/urls.py
from django.urls import path
from . import views

app_name = "drug_resistant"

urlpatterns = [
   path('',views.profile, name ="profile"),
    path('home0',views.home0, name ="home0"),
   path('home',views.home, name ="home"),
   path('home2',views.home2, name ="home2"),
   path('output',views.output, name ="output"),
   path('contact',views.contact, name ="contact"),
   path('search',views.search, name ="search"),
   path('error',views.output, name ="error"),
   path('output2',views.output2, name ="output2"),
   path('error2',views.output2, name ="error2"),
   path('error3',views.output2, name ="error3"),
   path('qsearch',views.qsearch, name ="qsearch"),
   path('QSoutput',views.qoutput, name ="qoutput"),
   path('faqs',views.faqs, name ="faqs"),
   path('browseinput',views.browseinput, name ="bin"),
   path('browseoutput',views.browseoutput, name ="bout"),
   path('pathway',views.pathway, name ="pw"),


]

virhost_lncr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ciods.urls')),
    path('contact/',include('contact.urls')),
    path('accounts/', include('accounts.urls', namespace='users')),
    path('drug_resistant/', include('drug_resistant.urls', namespace='drug_resistant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ciods/models.py
from django.db import models
from PIL import Image

class Ciods(models.Model):
    name = models.CharField(max_length = 255,null = True)
    designation = models.CharField(max_length = 255,null = True)
    Job_descritption = models.CharField(max_length = 2000,null = True)
    github_link = models.CharField(max_length = 255,null = True, blank = True)
    google_plus_link = models.CharField(max_length = 255,null = True, blank = True)
    linked_in_link = models.CharField(max_length = 255,null = True, blank = True)
    image = models.ImageField(upload_to = 'profiles/', null = True)
    level = models.IntegerField(default = 3)

    def save(self):
        super().save()  # saving image first
        img = Image.open(self.image.path) # Open image using self
        new_img = (400, 400)
        img.thumbnail(new_img)
        img.save(self.image.path)  # saving image at the same path

    def __str__(self):
        return self.name

class Publication(models.Model):
    publication = models.TextField(max_length = 5000, null = True)
    link = models.CharField(max_length = 1000, null = True, blank = True)
    journal = models.CharField(max_length = 100, null = True, blank = True)

    def __str__(self):
        return self.publication

ciods/views.py
from django.shortcuts import render ,redirect
from . models import Ciods , Publication

def ciods(request):

    director = Ciods.objects.filter(level = 1)
    professors = Ciods.objects.filter(level = 2)
    employees = Ciods.objects.filter(level = 3)
    pub_count = Publication.objects.all().count()

    context = {'employees':employees, 'director':director, 'professors':professors , 'pub_count':pub_count}
    return render(request,'ciods/home.html', context)

def pulblication(request):
    pulblications = Publication.objects.all()
    context = {'pulblications': pulblications}
    return render(request,'ciods/publications.html', context)

templates/ciods/ciods.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>CIODS</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'ciods/img/ciods-favicon.png' %}" rel="icon">
  <link href="{% static 'ciods/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'ciods/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'ciods/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'ciods/lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'ciods/lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'ciods/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'ciods/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

  <link href="{% static 'ciods/css/style.css' %}" rel="stylesheet">

</head>
<body>

  <!--==========================
  Header
  ============================-->
  <header id="header" class="fixed-top">
    <div class="container-fluid">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <h1 class="text-light"><a href="#header"><span>NewBiz</span></a></h1> -->
        <a href="{% url 'ciods:ciods' %}" class="scrollto">
          <img src="{% static 'ciods/img/ciods-logo.png' %}" alt="" class="img-fluid">
          <!-- <img src="{% static 'ciods/img/new logo.png' %}" alt="" class="img-fluid"> -->

        </a>
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'ciods:ciods' %}">Home</a></li>
          <li><a href="{% url 'ciods:pulblication' %}">Publications</a></li>
          <li><a href="">Career</a></li>
          <li><a href="#team">Team</a></li>
          <li class="drop-down"><a href="">Tools and Database</a>
            <ul>
              <li><a href="{% url 'drug_resistant:profile' %}"> Drug resistant </a></li>
           </ul>
          </li>
          <li><a href="#contact">Contact Us</a></li>
        </ul>
      </nav><!-- .main-nav -->

    </div>
  </header><!-- #header -->


{% block content %}


{% endblock %}

 <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row d-flex justify-content-center">

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>CIODS</h3>
              <p>
Center for Integrated Omics and Data Science (CIODS) is an initiative of the Yenepoya University envisioned (Yenvision-2025) to undertake the next-generation integrative omics research on various fields of Allopathic, Ayurvedic, Homeopathic and Naturopathic Sciences and also its integration to artificial intelligence for translational research.
              </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><a href="#">Home</a></li>
              <li><a href="#">About us</a></li>
              <li><a href="#">Services</a></li>
              <li><a href="#">Career</a></li>
              <li><a href="#">Publications</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>

            <p>
              4th floor,Yenepoya Ayurveda Medical <br>
              College and Hospital, Manjanady<br>
              Mangalore, 575018 <br>
              <strong>Phone:</strong> +918921377006<br>
              <strong>Email:</strong> ciods@yenepoya.edu.in <br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="github"><i class="fa fa-github"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>


        </div>
      </div>
    </div>
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>CIODS</strong>. All Rights Reserved
      </div>
      <div class="credits">

        by <a href="https://yenepoya.edu.in/" target="_blank">Yenepoya University</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  <script src="{% static 'ciods/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'ciods/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'ciods/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'ciods/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'ciods/lib/mobile-nav/mobile-nav.js' %}"></script>
  <script src="{% static 'ciods/lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'ciods/lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'ciods/lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'ciods/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'ciods/lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'ciods/lib/lightbox/js/lightbox.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <!-- <script src="{% static 'ciods/contactform/contactform.js' %}"></script> -->

  <!-- Template Main Javascript File -->
  <script src="{% static 'ciods/js/main.js' %}"></script>

</body>
</html>

templates/ciods/publications.html
{% extends 'ciods/ciods.html' %}

{% block content %}


<div class="container">
    <div class = "row">
        <div class=" col col-xl-12 col-lg-12">
            <div class = "d-flex justify-content-center">
                <h3 class="publications-head heading" style="color:blue; font-weight: bold;"> PUBLICATIONS </h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col col-xl-12 col-lg-12">
            <div class="d-flex justify-content-start">
                <h5> <b>  Total number of publications - 19
               </b> </h5>
            </div>
        </div>
        </div>


        <div class="row">
            <div class="col col-xl-12 col-lg-12">
                <div class="d-flex justify-content-start">
                    <h5> <b>  2023 (Number of publications- 9) 
                   </b> </h5>
                </div>
            </div>
            </div>
    



        <div class="row">

        <div class="col col-xl-12 col-lg-12">
    
            <!-- <ol class="publications">
                {% for p in pulblications %}

                <li>
                    {{ p.publication }}
                    {% if p.link %}
                    &nbsp;&nbsp;
                    <a href="{{ p.link }}" target="_blank">{{ p.journal }}</a>
                    {% endif %}
                </li>
                {% endfor%}
            </ol> -->

            <ol>
                <li>
                    <p>
                        Sanjeev, D., Dagamajalu, S., Shaji, V., George, M., Subbannayya, Y., Prasad, T.S., Raju, R. and Devasahayam Arokia Balaya, R., 2023. A network map of macrophage-stimulating protein (MSP) signaling. Journal of Cell Communication and Signaling, pp.1-8.
                        <a href="https://doi.org/10.1007/s12079-023-00755-w"><i>https://doi.org/10.1007/s12079-023-00755-w</i>. </a>
                    </p>

                </li>
                <li>
                    <p>
                        Upadhyay, S. S., Devasahayam Arokia Balaya, R., Parate, S. S., Dagamajalu, S., Keshava Prasad, T. S., Shetty, R., & Raju, R. (2023). An assembly of TROP2-mediated signaling events. Journal of cell communication and signaling, 10.1007/s12079-023-00742-1. Advance online publication.<a href="https://doi.org/10.1007/s12079-023-00742-1"><i>https://doi.org/10.1007/s12079-023-00742-1</i>. </a>
                    </p>

                </li>
                <li>
                    <p>V. Manjunath, S. G., Thenral, B. R., Lakshmi, A. N., A. Bassi, K. Priya Karthikeyan, K. Piyusha, R. Menon, A. Malhotra, L. S. Praveena, R. M. Anjanappa, S. M. Sakthivel Murugan, Kiran Polavarapu, Mainak Bardhan, V. Preethish-Kumar, Seena Vengalil, Saraswati Nashi, S. Sanga, M. Acharya, R. Raju, V. R. Pai, V. L. Ramprasad, R. Gupta. (2023). Large region of homozygous (ROH) identified in Indian patients with autosomal recessive limb girdle muscular dystrophy with p.Thr182Pro variant in SGCB gene. <i>Human mutation</i>. 
                    </p>

                </li>
                <li>
                    <p>Revikumar A. (2023). An Omics Strategy for Translational Bioinformatics and Rapid COVID-19 Drug Repurposing. <i>Omics : a journal of integrative biology</i>, 10.1089/omi.2022.0157. Advance online publication. 
                        <!-- <a href="https://doi.org/10.1089/omi.2022.0157" target="_blank">[doi]</a>  -->
                        [In press]
                        
                    </p>

                </li>
                <li>
                    <p>Abhinand, C. S., Galipon, J., Mori, M., Poornima, R., Prasad, T. S. K., Raju, R., Sudhakaran, P. R. and Tomita, M. (2023). Temporal phosphoproteomic analysis of VEGF-A signaling in HUVECs: An insight into early signaling events associated with angiogenesis. <i>Journal of Cell communication and Signaling</i>. [In press].
                    </p>

                </li>
                <li>
                    <p>Sankaran, D., Amjesh, R., Paul, A. M., George, B., Kala, R., Saini, S., & Kumar, R. (2023). Hyperactivation of p21-Activated Kinases in Human Cancer and Therapeutic Sensitivity. <i>Biomedicines</i>, 11(2), 462.
                        <!-- <a href="https://doi.org/10.3390/biomedicines11020462" target="_blank">[doi]</a> -->
                        [In press]
                    </p>

                </li>
                <li>
                    <p>Suchitha, G. P., Balaya, R. D. A., Raju, R., Keshava Prasad, T. S., & Dagamajalu, S. (2023). A network map of cytoskeleton-associated protein 4 (CKAP4) mediated signaling pathway in cancer. Journal of cell communication and signaling, 10.1007/s12079-023-00739-w. Advance online publication. <a href="https://doi.org/10.1007/s12079-023-00739-w">. <i>https://doi.org/10.1007/s12079-023-00742-1</i>.</a>
                    </p>

                </li>
                <li>
                    <p>Kumar, S., Rex, D. A. B., Saptami, K., Raju, R., T. S. Keshava Prasad., Kandasamy, R. K. (2023). Computational Tools for Exploring Peptide-Membrane Interactions in Gram-Positive Bacteria. <i>Computational and Structural Biotechnology Journal</i>.
                         <!-- <a href="https://doi.org/10.1016/j.csbj.2023.02.051" target="_blank">[doi]</a>  -->
                         [In press]
                    </p>

                </li>
                <li>
                    <p>Devasahayam Arokia Balaya, R., Chandrasekaran, J., Kanekar, S., Kumar Modi, P., Dagamajalu, S., Gopinathan, K., Raju, R., & Prasad, T. S. K. (2023). Calcium/calmodulin-dependent protein kinase kinase 2 (CAMKK2) inhibitors: a novel approach in small molecule discovery. Journal of biomolecular structure & dynamics, 1–11. Advance online publication. <a href="https://doi.org/10.1080/07391102.2023.2193999"> <i>https://doi.org/10.1080/07391102.2023.2193999</i>.</a>
                    </p>

                </li>
                <li>
                    <p>Mol, P., Balaya, R. D. A., Dagamajalu, S., Babu, S., Chandrasekaran, P., Raghavan, R., Suresh, S., Ravishankara, N., Raju, A. H., Nair, B., Modi, P. K., Mahadevan, A., Prasad, T. S. K., & Raju, R. (2023). A network map of GDNF/RET signaling pathway in physiological and pathological conditions. Journal of cell communication and signaling, Advance online publication.<a href="https://doi.org/10.1007/s12079-023-00726-1"</i>https://doi.org/10.1007/s12079-023-00726-1</a> </p>

                </li>
            </ol>




            </div>
        </div>

        <div class="row">
            <div class="col col-xl-12 col-lg-12">
                <div class="d-flex justify-content-start">
                    <h5> <b>  2022 (Number of publications- 10) 
                   </b> </h5>
                </div>
            </div>
            </div>


            
        <div class="row">

            <div class="col col-xl-12 col-lg-12">
                
            <ol>
                <li>
                    <p>
                        Dagamajalu, S., Rex, D. A. B., Suchitha, G. P., Rai, A. B., Kumar, S., Joshi, S., Raju, R., & Prasad, T. S. K. (2022). A network map of discoidin domain receptor 1(DDR1)-mediated signaling in pathological conditions. Journal of cell communication and signaling,  Advance online publication.<a href="https://doi.org/10.1007/s12079-022-00714-x"</i> https://doi.org/10.1007/s12079-022-00714-x</a>.
</p>

                </li>
                <li>
                    <p>Terlouw, Barbara., Blin, Kai., Navarro-Muñoz, Jorge C., Avalon, Nicole., Chevrette, Marc G., Egbert., ..Rex, D. A. B., ...Linington, Roger., Weber, Tilmann., Medema, Marnix. (2022). MIBiG 3.0: A community-driven effort to annotate experimentally validated biosynthetic gene clusters. <i>Nucleic Acids Research</i>. [In Press].
                    </p>

                </li>
                <li>
                    <p>Kumari, G., Rex, D. A. B., Goswami, S., Mukherjee, S., Biswas, S., Maurya, P., Jain, R., Garg, S., Prasad, T. S. K., Pati, S., Ramalingam, S., Mohandas, N., & Singh, S. (2022). Dynamic Palmitoylation of Red Cell Membrane Proteins Governs Susceptibility to Invasion by the Malaria Parasite, Plasmodium falciparum.ACS infectious diseases, 8(10), 2106–2118.<a href=" https://doi.org/10.1021/acsinfecdis.2c00199" </i>.<a href="https://doi.org/10.1021/acsinfecdis.2c00199" target="_blank">.https://doi.org/10.1021/acsinfecdis.2c00199</a>   

                    </p>

                </li>
                <li>
                    <p>Anam, Z., Kumari, G., Mukherjee, S., Rex, D. A. B., Biswas, S., Maurya, P., Ravikumar, S., Gupta, N., Kushawaha, A. K., Sah, R. K., Chaurasiya, A., Singhal, J., Singh, N., Kaushik, S., Prasad, T. S. K., Pati, S., Ranganathan, A., & Singh, S. (2022). Complementary crosstalk between palmitoylation and phosphorylation events in MTIP regulates its role during Plasmodium falciparum invasion. Frontiers in cellular and infection microbiology, 12, 924424. <a href="https://doi.org/10.3389/fcimb.2022.924424" target"_blank"> https://doi.org/10.3389/fcimb.2022.924424 </a>.
                    </p>

                </li>
                <li>
                    <p>Rex, D. A. B., Dagamajalu, S., Gouda, M. M., Suchitha, G. P., Chanderasekaran, J., Raju, R., Prasad, T. S. K., & Bhandary, Y. P. (2023). A comprehensive network map of IL-17A signaling pathway. Journal of cell communication and signaling, 17(1), 209–215. <a href="https//doi.org/10.1007/s12079-022-00686-y". target="_blank">https://doi.org/10.1007/s12079-022-00686-y</a>   
                    </p>

                </li>
                <li>
                    <p>Rex, D. A. B., Keshava Prasad, T. S., & Kandasamy, R. K. (2022). Revisiting Regulated Cell Death Responses in Viral Infections. International journal of molecular sciences, 23(13), 7023. https://doi.org/10.3390/ijms23137023</i>.<a href="https://doi.org/10.3390/ijms23137023" target="_blank">https://doi.org/10.3390/ijms23137023</a> 
                    </p>

                </li>
                <li>
                    <p>Antil, N., Arefian, M., Kandiyil, M. K., Awasthi, K., Prasad, T. S. K., & Raju, R. (2022). The Core Human MicroRNAs Regulated by Toxoplasma gondii. MicroRNA (Shariqah, United Arab Emirates), 11(2), 163–174. <a href="https://doi.org/10.2174/2211536611666220428130250" target="_blank">https://doi.org/10.2174/2211536611666220428130250</a>
                        
                    </p>

                </li>
                <li>
                    <p>Abhinand, C. S., Ibrahim, J., Keshava Prasad, T. S., Raju, R., Oommen, O. V., & Nair, A. S. (2022). Molecular docking and dynamics studies for the identification of Nipah virus glycoprotein inhibitors from Indian medicinal plants. Journal of biomolecular structure & dynamics, 1–8. Advance online publication.<a href="https://doi.org/10.1080/07391102.2022.2153169" target="_blank">https://doi.org/10.1080/07391102.2022.2153169</a></i>. </p>

                </li>
                <li>
                    <p>Ramesh, P., Babu, S., Ammankallu, S., Codi, J.A.K., Prasad, T. S. K., and Raju, R. (2023). "Helicobacter pylori regulated MicroRNA map of human gastric cells". <i>Helicobacter</i>. [In Press].</p>

                </li>
                <li>
                    <p>Abhinand, C. S., Prabhakaran, A. A., Krishnamurthy, A., Raju, R., Keshava Prasad, T. S., Nair, A. S., Rajasekharan, K. N., Oommen, O. V., & Sudhakaran, P. R. (2022). SARS-CoV-2 variants infectivity prediction and therapeutic peptide design using computational approaches. Journal of biomolecular structure & dynamics, 1–12. Advance online publication. <a href=" https://doi.org/10.1080/07391102.2022.2160819" target="_blank">https://doi.org/10.1080/07391102.2022.2153169</a></p>

                </li>
            </ol>

            </div>
        </div>


    </div>

</div>






{% endblock %}