ciods/urls.py
from django.urls import path
from . import views

app_name = 'ciods'

urlpatterns = [
path('',views.ciods, name = 'ciods'),
path('pulblication/',views.pulblication, name = 'pulblication'),

]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('contact/', views.contacts, name='contact'),
]

drug_resistant/urls.py
from django.urls import path
from . import views

app_name = "drug_resistant"

urlpatterns = [
   path('',views.profile, name ="profile"),
    path('home0',views.home0, name ="home0"),
   path('home',views.home, name ="home"),
   path('home2',views.home2, name ="home2"),
   path('output',views.output, name ="output"),
   path('contact',views.contact, name ="contact"),
   path('search',views.search, name ="search"),
   path('error',views.output, name ="error"),
   path('output2',views.output2, name ="output2"),
   path('error2',views.output2, name ="error2"),
   path('error3',views.output2, name ="error3"),
   path('qsearch',views.qsearch, name ="qsearch"),
   path('QSoutput',views.qoutput, name ="qoutput"),
   path('faqs',views.faqs, name ="faqs"),
   path('browseinput',views.browseinput, name ="bin"),
   path('browseoutput',views.browseoutput, name ="bout"),
   path('pathway',views.pathway, name ="pw"),


]

virhost_lncr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ciods.urls')),
    path('contact/',include('contact.urls')),
    path('accounts/', include('accounts.urls', namespace='users')),
    path('drug_resistant/', include('drug_resistant.urls', namespace='drug_resistant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

class Contacts(models.Model):
    name = models.CharField(max_length = 100 )
    email = models.EmailField(max_length = 100 )
    message = models.CharField(max_length = 255 )

    def __str__(self):
        return self.message

    class Meta:
        verbose_name_plural = 'Contacts'

drug_resistant/models.py
from django.db import models

# Create your models here.
class Drugs(models.Model):
    genes = models.CharField(max_length=2000, null=True)
    medicine = models.CharField(max_length=255, null= True)
    expression = models.CharField(max_length=255, null = True)
    
class Molecules(models.Model):
    pubMed = models.CharField(max_length=10, null=True)
    drug = models.CharField(max_length=80, null= True)
    cell_lo = models.CharField(max_length=255, null = True)
    control_cl = models.CharField(max_length=100, null = True)
    resistant_cl = models.CharField(max_length=100, null = True)
    molecules = models.CharField(max_length=100, null = True)
    name = models.CharField(max_length=100, null = True)
    gene_id = models.CharField(max_length=100, null = True)
    exp_inRes_cell = models.CharField(max_length=100, null = True)
    post_tm = models.CharField(max_length=100, null = True)
    driver_molecule = models.CharField(max_length=30, null = True)
    exp_method = models.CharField(max_length=100, null = True)
    fold_ratio = models.CharField(max_length=100, null = True)
    biomarker_type = models.CharField(max_length=100, null = True)
    pmid_marker = models.CharField(max_length=100, null = True)

contact/forms.py
from django.forms import ModelForm
from .models import Contacts

class ContactsForm(ModelForm):
    class Meta:
        model = Contacts
        fields = '__all__'

contact/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render , redirect
from django.core.mail import send_mail

from .forms import ContactsForm

def contacts(request):
    form = ContactsForm()
    if request.method == 'POST':
        form = ContactsForm(request.POST)
        if form.is_valid():
            form.save()
            message_name = request.POST['name']
            message_email = request.POST['email']
            message = request.POST['message']

            try:
                send_mail(
                    'Email from VirhostlncR website user:'+' '+message_email,
                    message,
                    message_email,
                    ['rajrrnbt@gmail.com','rexprem@yenepoya.edu.in','nisar.bb91@gmail.com']
                    )

                messages.info(request, 'Thank you for your feedback. We will get back to you ASAP.')
                return redirect('contact')

            except Exception:
                messages.info(request, 'Thank you for your feedback. We will get back to you ASAP.')
                return redirect('contact')


        else:
            messages.error(request, 'please enter valid information')

    context  = {'form': form }
    return render(request, 'contact/contactus.html',context)

drug_resistant/views.py
from django.shortcuts import render
from .models import Drugs , Molecules
import pandas as pd
import numpy as np
import json
from django.db.models import Q

def profile(request):
    return render(request, 'drug_resistant/profile.html',{})

def home0(request):
    return render(request, 'drug_resistant/home0.html',{})

def home(request):
    exp = Drugs.objects.all().values('expression').distinct()
    print(exp)
    return render(request, 'drug_resistant/home.html',{'exp': exp})

def home2(request):
    dname = Molecules.objects.all().values('drug').distinct()
    cline = Molecules.objects.all().values('cell_lo').distinct()
    print(dname)
    # hn = Drugs.objects.all().values('').distinct()
    return render(request, 'drug_resistant/home2.html',{'dname': dname, 'cline':cline})
   
   

def output(request):
    data = request.POST.get('sample1')
    print(data)
    data1 = request.POST.get('sample2')
    print(data1)
    genes = data.split()
    genes1 = data1.split()
    exp1 = 'Overexpression'
    exp2 = 'Downregulation '
    q1 = Q(genes__in=genes, expression=exp1)
    q2 = Q(genes__in=genes1, expression=exp2)

    combined_query = q1 | q2

    medicines = Drugs.objects.filter(combined_query).values()
            
               
    if not medicines:
        return render(request, 'drug_resistant/error.html',{})
    else:
        df = pd.DataFrame(list(medicines))
        df = df.groupby('genes').agg(pd.Series.tolist) 
        del df['id']
        df.reset_index(inplace=True)
        new_df = df.explode('medicine')
        new_df = (
            pd.crosstab(new_df['genes'], new_df['medicine'],
                        margins=True, margins_name='Total')
                .iloc[:-1]
                .rename_axis(columns=None)
                .reset_index()
        )
        drug_res=new_df.sort_values("Total")
        new_drugres = drug_res
        sum = new_drugres.sum()
        sum.name = 'Sum'
        new_drugres = new_drugres._append(sum.transpose())
        new_drugres = new_drugres.reset_index()          
        new_drugres = new_drugres.drop(['index'], axis=1)
        new_drugres.iat[-1,0] = 'Sum'
        new_drugres = new_drugres.set_index('genes').transpose()
        new_drugres = new_drugres.drop('Total')
        new_drugres=new_drugres.sort_values("Sum")
        new_drugres = new_drugres.drop('Sum', axis=1)
        genes = drug_res["genes"].tolist()
        drug_res = drug_res.drop('Total', axis=1)
        data = drug_res.drop('genes', axis=1)
        meds = data.columns.values.tolist()
        drug = ['Cisplatin', 'paclitaxel','5 fluorouracil', 'Gemcitabine', 'Pingyangmycin', 'Cetuximab', 'Docetaxel', 'Doxorubicin', 'Panobinostat']
        allDrug_list = set(drug) 
        drug_list = set(meds)  
        left_out_drugs = allDrug_list.difference(drug_list)  
        left_out_drugs = list(left_out_drugs)
        data = {'meds':left_out_drugs}
        rem_med = pd.DataFrame(data)
        rem_med.set_index('meds',inplace=True)
        rem_med1 = rem_med
        rem_med = rem_med.transpose()
        values = drug_res.set_index('genes')
        new_drugres = rem_med1._append(new_drugres)
        new_drugres = new_drugres.fillna(0)
        new_drugres = new_drugres.to_numpy()
        combined_data = rem_med._append(values)
        combined_data = combined_data.fillna(0)
        header_list = list(combined_data.columns)
        return render(request, 'drug_resistant/output.html',{'genes':genes,'n':header_list,'new_drugres':new_drugres})

def contact(request):
    return render(request, 'drug_resistant/contact.html',{})

def search(request):
    return render(request, 'drug_resistant/search.html',{})

def output2(request):
    molecule = request.POST.get('tf')
    print(molecule)
    if molecule == 'select':
        gene = request.POST.get('sample')
        gene = gene.split()
        print(gene)

    
        data = Molecules.objects.filter(name__in=gene).values()
        print(data)
        return render(request, 'drug_resistant/output2.html',{'data':data})

    else:
        gene = request.POST.get('sample')
        gene = gene.split()

        data = Molecules.objects.filter(name__in=gene,molecules = molecule).values()
        return render(request, 'drug_resistant/output2.html',{'data':data})

    
    


     
     
def qsearch(request):

    return render(request, 'drug_resistant/qsearch.html',{})
     
def qoutput(request):
    gene = request.POST.get('t1')
    selected_columns = request.POST.getlist('checkboxes')
    column_list = ['cell_lo','control_cl','exp_inRes_cell','exp_method','drug','driver_molecule','post_tm','fold_ratio','biomarker_type','pmid_marker']
    if 'select_all' in selected_columns:
        selected_columns = column_list
    gene_list = [gene]  # If gene is None, use an empty list
    data = Molecules.objects.filter(name__in=gene_list).values(*selected_columns)
    if not data:
        return render(request, 'drug_resistant/error.html',{})
        
   
    return render(request, 'drug_resistant/QSoutput.html',{'data':data, 'gene':gene})
    
def faqs(request):
    return render(request, 'drug_resistant/faqs.html',{})

def browseinput(request):
    drug = Molecules.objects.filter().values('drug').distinct()
    cancer =Molecules.objects.filter().values('cell_lo').distinct()
    molecule =Molecules.objects.filter().values('molecules').distinct()

    return render(request, 'drug_resistant/browseinput.html',{"drug":drug,"cell":cancer, "molecules":molecule})

def browseoutput(request): 
    drug = request.POST.getlist('selected_value1')
    drug = [json.loads(d.replace("'", "\"")) for d in drug]
    drug = [d['drug'] for d in drug]
    print(drug)

    cancer = request.POST.getlist('selected_value2')
    cancer = [d.replace("'", "\"").replace("\\xa0", " ") for d in cancer]
    cancer = [json.loads(d) for d in cancer]
    cancer = [d['cell_lo'] for d in cancer]
    print(cancer)

    molecule = request.POST.getlist('selected_value3')
    molecule = [json.loads(d.replace("'", "\"")) for d in molecule]
    molecule = [d['molecules'] for d in molecule]
    print(molecule)

    # query = Molecules.objects.all()

    # q1 = Q(genes__in=genes, expression=exp1)
    # q2 = Q(genes__in=genes1, expression=exp2)

    # combined_query = q1 | q2

    # medicines = Drugs.objects.filter(combined_query).values()

    # if drug:
    #     query = query.filter(drug__in=drug)
    # if cancer:
    #     query = query.filter(cell_lo__in=cancer)
    # if molecule:
    #     query = query.filter(molecules__in=molecule)


    # data = query.values()

    q1 = Q(drug__in=drug)
    q2 = Q(cell_lo__in=cancer)
    q3 = Q(molecules__in=molecule)

    combined_query = q1 | q2| q3

    data = Molecules.objects.filter(combined_query).values()

    if not data:
        return render(request, 'drug_resistant/error3.html', {"data": data})
    else:
        return render(request, 'drug_resistant/browseoutput.html', {"data": data})
    
def pathway(request):
    return render(request, 'drug_resistant/pathway.html', {})





   

templates/drug_resistant/QSoutput.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuickSearch</title>
    <!-- result.html -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.23.0/cytoscape.min.js" integrity="sha512-gEWKnYYa1/1c3jOuT9PR7NxiVI1bwn02DeJGsl+lMVQ1fWMNvtjkjxIApTdbJ/wcDjQmbf+McWahXwipdC9bGA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link href="/static/lncrna/styles.css" rel="stylesheet"/>
</head>

<body >
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand" href="{% url 'drug_resistant:profile' %}"> <h1>HNCDrugResDb</h1></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">

    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:home0' %}">HOME </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:bin' %}">BROWSE </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:home2' %}">BATCH QUERY</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:qsearch' %}">QUICK SEARCH </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:home' %}">ANALYZE </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:pw' %}">PATHWAY EXPLORER </a>
    </li>
    
    
    <li class="nav-item">
      <a class="nav-link " href="{% url 'drug_resistant:faqs' %}" >FAQs</a>
    </li>
        <li class="nav-item">
      <a class="nav-link " href="{% url 'drug_resistant:contact' %}" >Contact Us</a>
    </li>

  </ul>
  
</div>
</nav>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 8px;
        border: 1px solid #dddddd;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<table>
    <!-- The rest of the table as mentioned above -->
</table>

</head>
<body>
  <br>
    <h3 style="text-align: center;">The selected gene is {{gene}}</h3>
    <br>
<table>
    <thead>
        <tr>
            <th>Cell LO</th>
            <th>Control CL</th>
            <th>Exp in Res Cell</th>
            <th>Exp Method</th>
            <th>Drug</th>
            <th>Driver Molecule</th>
            <th>Post TM</th>
            <th>Fold Ratio</th>
            <th>Biomarker Type</th>
            <th>PMID Marker</th>
        </tr>
    </thead>
    <tbody>
        {% for row in data %}
            <tr>
                {% for value in row.values %}
                    <td>{{ value }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>


</body>
</html>

templates/drug_resistant/browseinput.html
{% extends "drug_resistant/base.html" %}

{% block content %}
<style>
  /* Custom CSS for the columns */
  .column-box {
    border: 2px solid rgb(182, 232, 245);
    padding: 10px; /* Optional: Add padding to create some space between the border and the content */
    overflow-y: scroll;
    max-width: 65em; 
    max-height: 500px; 
    /* Adjust the maximum height as needed */
    /* You can also add additional styles for smaller containers, if required */
  }
  .container {
    margin-top: 50px;
   
  }
</style>

<body>
    <form action="{% url 'drug_resistant:bout' %}" method = 'POST'>{% csrf_token %}
  <div class="container">
    <div class="mt-3 row">
      <div class="col-sm column-box">
        <center><b>Drug Name</b></center>
        {% for value in drug %}
            <label>
                <input type="checkbox" name="selected_value1" value="{{ value }}">
                {{ value.drug }}
            </label>
            <br>
        {% endfor %}
      </div>
      <div class="col-sm column-box">
        <center><b>Cancer Type</b></center>
        {% for value in cell %}
            <label>
                <input type="checkbox" name="selected_value2" value="{{ value }}">
                {{ value.cell_lo }}
            </label>
            <br>
        {% endfor %}
      </div>   
      <div class="col-sm column-box">
        <center><b>Molecule Type</b></center>
        {% for value in molecules %}
            <label>
              {% if value.molecules == 'RNA' %}
              <input type="checkbox" name="selected_value3" value="{{ value }}">
              mRNA
            {% elif value.molecules == 'Circ' %}
              <input type="checkbox" name="selected_value3" value="{{ value }}">
              CircRNA
            {% else %}
              <input type="checkbox" name="selected_value3" value="{{ value }}">
              {{ value.molecules }}
            {% endif %}

            </label>
            <br>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class=" d-flex justify-content-center">
    <input  class="btn btn-danger btn-lg mt-4" type="reset" > &nbsp;&nbsp;
    <input  class="btn btn-info btn-lg mt-4" type="submit" >
  </div>
</form>
</body>

{% endblock %}

templates/drug_resistant/browseoutput.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data </title>

    <style>
       table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 8px;
        border: 1px solid #dddddd;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    </style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.23.0/cytoscape.min.js" integrity="sha512-gEWKnYYa1/1c3jOuT9PR7NxiVI1bwn02DeJGsl+lMVQ1fWMNvtjkjxIApTdbJ/wcDjQmbf+McWahXwipdC9bGA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link href="/static/lncrna/styles.css" rel="stylesheet"/>
</head>

<body >
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand" href="{% url 'drug_resistant:profile' %}"> <h1>HNCDrugResDb</h1></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">

    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:home0' %}">HOME </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'drug_resistant:bin' %}">BROWSE </a>
      </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:home2' %}">BATCH QUERY</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:qsearch' %}">QUICK SEARCH </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:home' %}">ANALYZE </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'drug_resistant:pw' %}">PATHWAY EXPLORER </a>
    </li>
    
    
    <li class="nav-item">
      <a class="nav-link " href="{% url 'drug_resistant:faqs' %}" >FAQs</a>
    </li>
        <li class="nav-item">
      <a class="nav-link " href="{% url 'drug_resistant:contact' %}" >Contact Us</a>
    </li>

  </ul>
  
</div>
</nav>



    <!--Solution no 1.a-->

    <table id="data-table" border=1 cellpadding=7 style="border-collapse:collapse; text-align:center">
        

        <tr>
            
            <th>Drug</th>
            <th>Cell Line Origin</th>
            <th>Control Cell Line</th>
            <th>Resistant Cell Line</th>
            <th>Molecules</th>
            <th>Name</th>
            <th>Gene ID</th>
            <th>Expression in resistant cell</th>
            <th>Post-translational modification(s)</th>
            <th>Driver molecule of Drug resistance (Validated)</th>
            <th>Experimental method</th>
            <th>Fold Ratio</th>
            <th>Biomarker Type</th>
            <th>PMID Marker</th>
            <th>PubMed ID</th>



        </tr>
        
        {% for mol in data %}
        <tr>
            
            <td>{{ mol.drug }}</td>
            <td>{{ mol.cell_lo }}</td>
            <td>{{ mol.control_cl }}</td>
            <td>{{ mol.resistant_cl }}</td>
            <td>{{ mol.molecules }}</td>
            <td>{{ mol.name }}</td>
            <td>{{ mol.gene_id }}</td>
            <td>{{ mol.exp_inRes_cell }}</td>
            <td>{{ mol.post_tm }}</td>
            <td>{{ mol.driver_molecule }}</td>
            <td>{{ mol.exp_method }}</td>
            <td>{{ mol.fold_ratio }}</td>
            <td>{{ mol.biomarker_type }}</td>
            <td>{{ mol.pmid_marker }}</td>
            <td>{{ mol.pubMed }}</td>
        </tr>
        {% endfor %}
    </table>

</body>

<script>
  window.addEventListener("DOMContentLoaded", function() {
      function setNavbarWidth() {
          const tableWidth = document.getElementById("data-table").offsetWidth;
          const navbar = document.querySelector(".navbar");
          navbar.style.width = `${tableWidth}px`;
      }

      // Call the function initially and whenever the window is resized
      setNavbarWidth();
      window.addEventListener("resize", setNavbarWidth);
  });
</script>


</html>